from discord import Bot, InputText, Embed
from pycordViews import EasyModal, Pagination

async def callback_function(ui: InputText, interaction):
    await interaction.response.send_message(f"You entered: {ui.value}", ephemeral=True)

a = 0

def make_content() -> str:
    return "This is a dynamic content generated by a function."

def make_embed() -> Embed:
    global a
    embed = Embed(title="Dynamic Embed", description=f"This embed{a} is generated by a function.", color=0x00ff00)
    a += 1
    return embed

def setup(bot: Bot):

    @bot.command()
    async def test(ctx):
        pagination = Pagination()
        pagination.add_page(content="This is the first page")
        pagination.add_page(content=make_content)
        pagination.add_page(content="This is the third page", embed=make_embed)
        await pagination.send(target=ctx.channel)